# Generated by Django 2.2.3 on 2020-09-23 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200921_0646'),
    ]

    operations = [
        migrations.AddField(
            model_name='userblog',
            name='forget_password_code',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
