# Generated by Django 2.2.3 on 2020-09-24 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_userblog_forget_password_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='userblog',
            name='forget_password_code_expiration',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
